version: "3.9"
services:

  postgres:
    image: postgres
    env_file: ./postgres/.env
    volumes:
      - ./pg-data:/var/lib/postgresql/data/pgdata
      - .:/postgres/docker-entrypoint-initdb.d
    networks:
      - db-network
    restart: on-failure
    ports:
      - "5432:5432"
      
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - db-network
      - app-network
    restart: on-failure
    depends_on:
      - postgres
    links:
      - "postgres:db"

  nginx:
    build: ./nginx
    networks:
      - internet
      - app-network
    restart: on-failure
    depends_on:
      - backend
    ports:
      - "80:80"

networks:
  db-network:
    driver: bridge
    internal: true
  app-network:
    driver: bridge
    internal: true
  internet: 
    driver: bridge
    

    
